### ISSUE TITLE
Connecting to Raspberry Pi results in no noticable change

### ISSUE THREAD

**Issue by roryyamm** [fgalliat/XtsTiLink_gh#2]
Right. So I've finally got the entire system assembled:
![dsc00003](https://user-images.githubusercontent.com/24758288/32296376-7b1b03b4-bf22-11e7-88d2-c587b86cbee0.JPG)
With the only difference between the original schematic and my version being the subbing in of one 2000ohm resistor with two 1000ohm resistors. 
Unfortunately, when I attempt to connect the apparatus to my Raspberry Pi (A model 2 B) Via an old PATA cable, turn on both the Pi and the Arduino (in no particular order; the order doesn't seem to affect the outcome), connect my calculator and turn on your terminal program… nothing happens. Occasionally, the 'L' Light slowly pulses, after pressing or tripping the reset button, but nothing appears on the calculator end. Checking and rechecking the connections (Redoing them entirely several times) causes no change in the situation.
Two questions:
1. What does the board do when properly working?
2. How do you turn it on? Calculator first, then Arduino, then Pi? Pi, then Arduino, then Calculator? some other combination?

EDIT: I have realised that more software on the Pi side is needed. As this is also not  working, I think I'd best file a ticket there after a few days of blindly trying to make it work.

**Comment by fgalliat** [comment]
look @ tools/ directory there are some utilities written in Java
